name: Nest.js Comments microservice
on:
    push:
        branches: ['main']
    pull_requests:
        branches: ['main']

    jobs:
        deploy:
            runs_on: ubuntu-latest
            steps:
                - name: Checkout scm
                  uses: actions/checkout@v3

                - name: install kubectl
                  uses: azure/setup-kubectl@v2.0
                  with:
                      version: 'v1.24.0'
                  id: install

                - name: Configure AWS credentials
                  uses: aws-actions/configure-aws-credentials@v1
                  with:
                      aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
                      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

                - name: Log in to Amazon ECR
                  id: login-ecr
                  uses: aws-actions/amazon-ecr-login@v1

                - name: Build and push image to Amazon ECR
                  env:
                      REGISTRY: ${{steps.login-ecr.outputs.registry}}
                      REPOSITORY: comments-comments
                      IMAGE_TAG: 1.1
                  run: |
                      docker build -t $REGISTRY/$REPOSITORY.$IMAGE_TAG .
                      docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

                - name: Update kube config
                  run: aws eks update-kubeconfig --name comments-cluster

                - name: Deploy to EKS
                  run: |
                      kubectl apply -f ./k8s/deployment.yaml
                      kubectl apply -f ./k8s/service.yaml
